-- Criando tabelas

CREATE TABLE Executante (
    ID_EXECUTANTE INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_PESSOA INT,
    CPF_CNPJ VARCHAR(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP
);

CREATE TABLE Servico (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EXECUTANTE INT,
    TIPO_SERVICO INT,
    DESCRICAO VARCHAR(200),
    SITUACAO VARCHAR(10),
    FOREIGN KEY (ID_EXECUTANTE) REFERENCES Executante(ID_EXECUTANTE)
);