-- Criando tabelas

INSERT INTO Executante (TIPO_PESSOA, CPF_CNPJ, NOME, CRIADO_EM)
VALUES (1, 15414748522, 'PESSOA FISICA 1', CURDATE());

INSERT INTO Executante (TIPO_PESSOA, CPF_CNPJ, NOME, CRIADO_EM)
VALUES (2, 15414748000130, 'PESSOA JURIDICA 1', CURDATE());

INSERT INTO Servico (ID_EXECUTANTE, TIPO_SERVICO, DESCRICAO, SITUACAO)
VALUES (1, 10, 'LIMPEZA', 'CADASTRADO');