name: Deploy Actions
on:
  push:
    branches:
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Root1234
          MYSQL_DATABASE: gerenciamento_servicos
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do código
          uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes unitários
        run: mvn test

      - name: Generate JaCoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

      - name: Log coverage percentage
        run:
          echo "coverage = ${{ steps.jacoco.ouputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: unit-test

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Root1234
          MYSQL_DATABASE: gerenciamento_servicos
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build com Maven
        run: mvn -B clean install