name: Deploy Actions
on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Root1234
          MYSQL_DATABASE: gerenciamento_servicos
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build com Maven
        run: mvn -B clean install

      - name: Executar testes unitários
        run: mvn test
